version: '3.8'

services:
  seats-app:
    build: .
    container_name: seats-automation
    
    ports:
      - "127.0.0.1:8085:8085"

    volumes:

      - ./data:/app/data
      - ./request-logs:/app/request-logs