version: '3.8'

services:
  seats-app:
    build: .
    container_name: seats-automation
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - ./seats_app.db:/app/seats_app.db
      
      - ./request-logs:/app/request-logs