version: '3.8'

services:
  seats-app:
    build: .
    container_name: seats-automation
    environment:
      - API_HOST=01v2mobileapi.seats.cloud
    ports:
      - "127.0.0.1:8085:8085"
    volumes:
      - ./seats_app.db:/app/seats_app.db
      - ./request-logs:/app/request-logs